-- ============================================================================
-- UNIPULSE — SEED DATA
-- Run this AFTER schema.sql. Countries are already seeded inside schema.sql.
-- This file adds all 147 seed universities from the brief.
--
-- IMPORTANT — data honesty:
-- Every university below is inserted with data_confidence = 'unavailable' and
-- priority_tier = 3 ("smaller but viable, needs market testing"). No student
-- counts, international %, or postgrad numbers are guessed — the brief is
-- explicit that these must come from HESA / IRCC-StatCan / Australian Dept of
-- Education / IIE Open Doors-IPEDS, or be left blank. Fill those fields in
-- from the admin dashboard (or directly in Supabase) as you gather real data,
-- and the opportunity_score recalculates automatically.
--
-- The one exception: priority_tier is bumped to 1 below for a short list of
-- globally well-known research-intensive universities. That's an editorial
-- starting point for where to focus first outreach, not a data claim —
-- re-tier freely once real numbers come in.
-- ============================================================================
insert into universities (name, slug, country_id, priority_tier, data_confidence) values
  ('Imperial College London', 'imperial-college-london', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('London School of Economics and Political Science', 'lse', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University College London', 'ucl', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Warwick', 'warwick', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Manchester', 'university-of-manchester', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Edinburgh', 'university-of-edinburgh', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Southampton', 'university-of-southampton', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Leeds', 'university-of-leeds', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Bath', 'university-of-bath', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Glasgow', 'university-of-glasgow', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Lancaster University', 'lancaster-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Strathclyde', 'university-of-strathclyde', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Durham University', 'durham-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Cranfield University', 'cranfield-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Aston University', 'aston-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('City University of London', 'city-university-of-london', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Queen Mary University of London', 'queen-mary-university-of-london', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Exeter', 'university-of-exeter', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Nottingham Trent University', 'nottingham-trent-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Sheffield', 'university-of-sheffield', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Brunel University London', 'brunel-university-london', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Kent', 'university-of-kent', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Reading', 'university-of-reading', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Essex', 'university-of-essex', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Heriot-Watt University', 'heriot-watt-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Surrey', 'university-of-surrey', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Portsmouth', 'university-of-portsmouth', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Manchester Metropolitan University', 'manchester-metropolitan-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Birmingham', 'university-of-birmingham', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Cardiff University', 'cardiff-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Oxford', 'university-of-oxford', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Cambridge', 'university-of-cambridge', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('King''s College London', 'king-s-college-london', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Newcastle University', 'newcastle-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Nottingham', 'university-of-nottingham', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Liverpool', 'university-of-liverpool', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Leicester', 'university-of-leicester', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Sussex', 'university-of-sussex', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Stirling', 'university-of-stirling', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Aberdeen', 'university-of-aberdeen', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of East Anglia', 'university-of-east-anglia', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Hull', 'university-of-hull', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Plymouth', 'university-of-plymouth', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Bournemouth University', 'bournemouth-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Westminster', 'university-of-westminster', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Middlesex University', 'middlesex-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Greenwich', 'university-of-greenwich', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Coventry University', 'coventry-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Hertfordshire', 'university-of-hertfordshire', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Sheffield Hallam University', 'sheffield-hallam-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Leeds Beckett University', 'leeds-beckett-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Liverpool John Moores University', 'liverpool-john-moores-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Robert Gordon University', 'robert-gordon-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Ulster University', 'ulster-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Swansea University', 'swansea-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Keele University', 'keele-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('De Montfort University', 'de-montfort-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Anglia Ruskin University', 'anglia-ruskin-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Oxford Brookes University', 'oxford-brookes-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Edge Hill University', 'edge-hill-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('Teesside University', 'teesside-university', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Bedfordshire', 'university-of-bedfordshire', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Wolverhampton', 'university-of-wolverhampton', (select id from countries where code = 'UK'), 3, 'unavailable'),
  ('University of Toronto', 'university-of-toronto', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('UBC', 'ubc', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('McGill', 'mcgill', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Waterloo', 'waterloo', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Alberta', 'university-of-alberta', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('McMaster University', 'mcmaster-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Western University', 'western-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('York University', 'york-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Toronto Metropolitan University', 'toronto-metropolitan-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Ottawa', 'university-of-ottawa', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Queen''s', 'queen-s', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Calgary', 'university-of-calgary', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Simon Fraser University', 'simon-fraser-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Concordia University', 'concordia-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Manitoba', 'university-of-manitoba', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Saskatchewan', 'university-of-saskatchewan', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Dalhousie University', 'dalhousie-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Windsor', 'university-of-windsor', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Carleton University', 'carleton-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Wilfrid Laurier University', 'wilfrid-laurier-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Guelph', 'university-of-guelph', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Memorial University of Newfoundland', 'memorial-university-of-newfoundland', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Brock University', 'brock-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('Ontario Tech University', 'ontario-tech-university', (select id from countries where code = 'CA'), 3, 'unavailable'),
  ('University of Melbourne', 'university-of-melbourne', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Monash University', 'monash-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('University of Sydney', 'university-of-sydney', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('UNSW Sydney', 'unsw-sydney', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Australian National University', 'australian-national-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('University of Queensland', 'university-of-queensland', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('University of Technology Sydney', 'university-of-technology-sydney', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('RMIT University', 'rmit-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Deakin University', 'deakin-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Macquarie University', 'macquarie-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('University of Wollongong', 'university-of-wollongong', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Queensland University of Technology', 'queensland-university-of-technology', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Curtin University', 'curtin-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('University of Adelaide', 'university-of-adelaide', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('La Trobe University', 'la-trobe-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Griffith University', 'griffith-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Swinburne University of Technology', 'swinburne-university-of-technology', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Western Sydney University', 'western-sydney-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('University of South Australia', 'university-of-south-australia', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Newcastle University', 'newcastle-university-1', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Flinders University', 'flinders-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Victoria University', 'victoria-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Murdoch University', 'murdoch-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('Edith Cowan University', 'edith-cowan-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('James Cook University', 'james-cook-university', (select id from countries where code = 'AU'), 3, 'unavailable'),
  ('New York University', 'new-york-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Northeastern University', 'northeastern-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Columbia University', 'columbia-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Southern California', 'university-of-southern-california', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Illinois Urbana-Champaign', 'university-of-illinois-urbana-champaign', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Purdue University', 'purdue-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Michigan', 'university-of-michigan', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('UC Berkeley', 'uc-berkeley', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('UCLA', 'ucla', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('UC San Diego', 'uc-san-diego', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Washington', 'university-of-washington', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Texas at Dallas', 'university-of-texas-at-dallas', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Texas at Austin', 'university-of-texas-at-austin', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Texas at Arlington', 'university-of-texas-at-arlington', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Arizona State University', 'arizona-state-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Arizona', 'university-of-arizona', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Maryland', 'university-of-maryland', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Pennsylvania', 'university-of-pennsylvania', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Boston University', 'boston-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University at Buffalo', 'university-at-buffalo', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('UMass Amherst', 'umass-amherst', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Minnesota', 'university-of-minnesota', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Wisconsin-Madison', 'university-of-wisconsin-madison', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Penn State University', 'penn-state-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Rutgers University', 'rutgers-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Texas A&M University', 'texas-a-m-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Carnegie Mellon University', 'carnegie-mellon-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Georgia Institute of Technology', 'georgia-institute-of-technology', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Florida', 'university-of-florida', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('UNC Charlotte', 'unc-charlotte', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('University of Cincinnati', 'university-of-cincinnati', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Drexel University', 'drexel-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('George Washington University', 'george-washington-university', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Illinois Institute of Technology', 'illinois-institute-of-technology', (select id from countries where code = 'US'), 3, 'unavailable'),
  ('Stevens Institute of Technology', 'stevens-institute-of-technology', (select id from countries where code = 'US'), 3, 'unavailable');

-- ----------------------------------------------------------------------------
-- Editorial tier-1 starting list (well-known, large, internationally-recruiting
-- research universities — re-tier as real data arrives)
-- ----------------------------------------------------------------------------
update universities set priority_tier = 1 where slug in (
  'imperial-college-london','london-school-of-economics-and-political-science','university-college-london',
  'university-of-warwick','university-of-manchester','university-of-edinburgh','university-of-oxford',
  'university-of-cambridge','king-s-college-london',
  'university-of-toronto','ubc','mcgill','university-of-waterloo',
  'university-of-melbourne','monash-university','university-of-sydney','unsw-sydney','australian-national-university',
  'new-york-university','columbia-university','university-of-southern-california','university-of-michigan',
  'uc-berkeley','ucla','university-of-washington','carnegie-mellon-university','georgia-institute-of-technology'
);
